# Generated by Django 4.1.1 on 2022-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_delete_estimate"),
        ("buy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=30)),
                ("material", models.CharField(max_length=15)),
                ("method", models.CharField(max_length=15)),
                ("pieces", models.IntegerField()),
                ("detail", models.TextField()),
                ("drawing", models.FileField(upload_to="")),
                ("reg_date", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(name="Buyer",),
    ]
