# Generated by Django 4.1.1 on 2022-11-01 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sell', '0001_initial'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_id', models.UUIDField(default=uuid.uuid4)),
                ('bid_id', models.UUIDField(default=uuid.uuid4)),
                ('success_date', models.DateTimeField()),
                ('product_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=15)),
                ('method', models.CharField(max_length=15)),
                ('pieces', models.IntegerField()),
                ('detail', models.TextField()),
                ('drawing', models.FileField(upload_to='')),
                ('reg_date', models.DateTimeField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_id', models.UUIDField()),
                ('price', models.IntegerField()),
                ('bid_date', models.DateTimeField()),
                ('finished', models.BooleanField()),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller')),
            ],
        ),
    ]
