# Generated by Django 4.1.1 on 2022-11-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='estimate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.estimate'),
        ),
    ]
