# Generated by Django 4.1.1 on 2022-10-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Estimate",),
    ]
