# Generated by Django 4.1.1 on 2022-11-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_bid_seller_id_alter_estimate_buyer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='product_state',
            field=models.CharField(max_length=20),
        ),
    ]
