# Generated by Django 4.1.1 on 2022-11-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_bid_seller_id_remove_estimate_buyer_id_and_more'),
        ('trade', '0003_alter_trade_estimate_id'),
    ]

    operations = [
    ]
