# Generated by Django 4.1.1 on 2022-10-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('PW', models.CharField(max_length=30)),
                ('TEL', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('equipment_id1', models.CharField(max_length=50)),
                ('equipment_id2', models.CharField(max_length=50)),
                ('equipment_id3', models.CharField(max_length=50)),
                ('equipment_id4', models.CharField(max_length=50)),
                ('equipment_id5', models.CharField(max_length=50)),
                ('equipment_id6', models.CharField(max_length=50)),
                ('equipment_id7', models.CharField(max_length=50)),
                ('equipment_id8', models.CharField(max_length=50)),
                ('equipment_id9', models.CharField(max_length=50)),
                ('equipment_id10', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentToSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.equipment')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller')),
            ],
        ),
    ]
