# Generated by Django 4.1.1 on 2022-11-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="equipment_id1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id10",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id3",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id4",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id5",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id6",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id7",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id8",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seller",
            name="equipment_id9",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
